### ISSUE TITLE
Uncaught SyntaxError with Barcode_Result-O

### ISSUE THREAD

**Issue by kigison** [Fritingo/IoTtalk_github_page_running#1]
There are 2 error Msg here.
ida.js(line70) _"var data_value = JSON.parse(data[1]);"_   It is necessary to add exception handling.

Uncaught SyntaxError: Unexpected token '查', "查無此病人資訊" is not valid JSON

> at JSON.parse (<anonymous>)
> at Object.Barcode_Result_O [as Barcode_Result-O] (ida.js:70:43)
> at pull (dai.js:63:31)
> at pull_odf_callback (dan.js:153:17)
> at Object.<anonymous> (csmapi.js:58:17)
> at i (jquery.js:2:27603)
> at Object.fireWith [as resolveWith] (jquery.js:2:28369)
> at A (jquery.js:4:13858)
> at XMLHttpRequest.<anonymous> (jquery.js:4:16146)

Uncaught SyntaxError: Unexpected token '查', "查無此藥品資訊" is not valid JSON

>       at JSON.parse (<anonymous>)
>       at Object.Barcode_Result_O [as Barcode_Result-O] (ida.js:70:43)
>       at pull (dai.js:63:31)
>       at pull_odf_callback (dan.js:153:17)
>       at Object.<anonymous> (csmapi.js:58:17)
>       at i (jquery.js:2:27603)
>       at Object.fireWith [as resolveWith] (jquery.js:2:28369)
>       at A (jquery.js:4:13858)
>       at XMLHttpRequest.<anonymous> (jquery.js:4:16146)

**Comment by Fritingo** [comment]
We need more details

**Comment by kigison** [comment]
If incorrect Barcode information is entered on the Edge Device, the DAI from the Database will return "查無此病人資訊" or "查無此藥品資訊".

And these strings cannot be converted into JSON format.

**Comment by ann88412a** [comment]
Fixed
