### ISSUE TITLE
html5QrcodeScanner Error

### ISSUE THREAD

**Issue by kigison** [Fritingo/IoTtalk_github_page_running#2]
The html5QrcodeScanner needs to be cleaned up more thoroughly.

Err Msg:
_Uncaught HTML Element with id=reader not found  html5-qrcode.min.js:2_

**Comment by Fritingo** [comment]
fixed
https://github.com/Fritingo/MedicationTalk_Platform/commit/7ff236f5aef37585024c689410a7db4bc840c5fd
